"""add notification system

Revision ID: 1b22793431d7
Revises: 508b0956b07d
Create Date: 2026-09-15 11:23:31.472834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b22793431d7'
down_revision: Union[str, Sequence[str], None] = '508b0956b07d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('category', sa.Enum('ACCOUNT', 'SECURITY', 'JOB', 'PROPOSAL', 'CONTRACT', 'MILESTONE', 'REVIEW', name='notification_category'), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_notification_events_idempotency_key')
    )
    op.create_index(op.f('ix_notification_events_category'), 'notification_events', ['category'], unique=False)
    op.create_index(op.f('ix_notification_events_event_type'), 'notification_events', ['event_type'], unique=False)
    op.create_index('ix_notification_events_recipient_created_at', 'notification_events', ['recipient_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notification_events_recipient_id'), 'notification_events', ['recipient_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('ACCOUNT', 'SECURITY', 'JOB', 'PROPOSAL', 'CONTRACT', 'MILESTONE', 'REVIEW', name='notification_category'), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', name='notification_channel'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', 'channel', name='uq_notification_pref_user_category_channel')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', name='notification_channel'), nullable=False),
    sa.Column('destination_masked', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'SKIPPED', name='notification_delivery_status'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['notification_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'channel', name='uq_notification_deliveries_event_channel')
    )
    op.create_index(op.f('ix_notification_deliveries_event_id'), 'notification_deliveries', ['event_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_status'), 'notification_deliveries', ['status'], unique=False)
    op.create_index('ix_notification_deliveries_status_next_attempt_at', 'notification_deliveries', ['status', 'next_attempt_at'], unique=False)
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('users', 'phone')
    op.drop_index(
        'ix_notification_deliveries_status_next_attempt_at',
        table_name='notification_deliveries',
    )
    op.drop_index(
        op.f('ix_notification_deliveries_status'),
        table_name='notification_deliveries',
    )
    op.drop_index(
        op.f('ix_notification_deliveries_event_id'),
        table_name='notification_deliveries',
    )
    op.drop_table('notification_deliveries')
    op.drop_index(
        op.f('ix_notification_preferences_user_id'),
        table_name='notification_preferences',
    )
    op.drop_table('notification_preferences')
    op.drop_index(
        op.f('ix_notification_events_recipient_id'),
        table_name='notification_events',
    )
    op.drop_index(
        'ix_notification_events_recipient_created_at',
        table_name='notification_events',
    )
    op.drop_index(
        op.f('ix_notification_events_event_type'),
        table_name='notification_events',
    )
    op.drop_index(
        op.f('ix_notification_events_category'),
        table_name='notification_events',
    )
    op.drop_table('notification_events')