"""add avatar_url to freelancer_profiles

Revision ID: 4fa376e5e13d
Revises: 9ec60233135d
Create Date: 2026-09-09 18:15:54.790709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fa376e5e13d'
down_revision: Union[str, Sequence[str], None] = '9ec60233135d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freelancer_profiles', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('freelancer_profiles', 'avatar_url')
    # ### end Alembic commands ###
