"""add deliverable_url to milestones

Revision ID: 6538a9ed72e0
Revises: 4fa376e5e13d
Create Date: 2026-09-10 11:31:27.361681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6538a9ed72e0'
down_revision: Union[str, Sequence[str], None] = '4fa376e5e13d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestones', sa.Column('deliverable_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milestones', 'deliverable_url')
    # ### end Alembic commands ###
